<?php

namespace backend\controllers;


use app\models\AlphaTest;
use app\models\AlphaUsers;
use backend\controllers\core\BaseController;
use backend\service\core\CurdService;
use Yii;

class TestController extends BaseController
{
    function beforeAction($action)
    {   self::setTitle("TEST");
        self::setTab1("T1");
        self::setTab2("T2");
        CurdService::setModel(new AlphaTest());
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $req = Yii::$app->request;
        $where['condition']['id'] = $req->get("id");
        $where['condition']['type'] = $req->get("type");
        $where['s_date'] = $req->get("s_date");
        $where['e_date'] = $req->get('e_date');
        $res=CurdService::getDataList($where,'*');
        return $this->render('index2', $res);
    }
}