<?php

namespace backend\controllers;


use app\models\AlphaTest;
use app\models\AlphaUsers;
use backend\controllers\core\BaseController;
use backend\service\core\CurdService;
use backend\service\TestService;
use Yii;

class TestController extends BaseController
{
    function beforeAction($action)
    {
        CurdService::setPkId("id");
        CurdService::setModel(new AlphaTest());
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        self::setTitle("TEST");
        self::setTab1("T1");
        self::setTab2("T2");

        $req = Yii::$app->request;
        $where['condition']['id'] = $req->get("id");
        $where['condition']['type'] = $req->get("type");
        $where['s_date'] = $req->get("s_date");
        $where['e_date'] = $req->get('e_date');
        $res=CurdService::getDataList($where,'*');
        return $this->render('index2', $res);
    }

    function actionAdd()
    {
        $req = \Yii::$app->request;
        $res = TestService::add($req->post());
        if (!$res) {
            self::warning(TestService::getErr());
        }
        self::output("添加成功");
    }

    function actionEditP($id = null)
    {
        $res = TestService::getOne($id);
        return $this->render('edit', $res);
    }

    function actionUpdate()
    {
        $req = \Yii::$app->request;
        $res = TestService::edit($req->post());
        if (!$res) {
            self::warning(TestService::getErr());
        }
        self::output("编辑成功");
    }

    function actionDelete($id = null)
    {
        $res = TestService::del($id);
        if (!$res) {
            self::warning(TestService::getErr());
        }
        self::output("删除成功");
    }
}