<?php

namespace backend\controllers;


use app\models\AlphaTest;
use backend\controllers\core\BaseController;
use backend\service\core\CurdService;

class TestController extends BaseController
{
    function beforeAction($action)
    {
        self::setPannelTitle("panel标题");
        CurdService::setModel(AlphaTest::tableName());
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}